// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import "@vue/runtime-core";

declare module "@vue/runtime-core" {
  export interface GlobalComponents {
    BlinText: typeof import("./components/BlinText.vue")["default"];
    Confetti: typeof import("./components/Confetti.vue")["default"];
    Counter: typeof import("./components/Counter.vue")["default"];
    Footer: typeof import("./components/Footer.vue")["default"];
    PageLoading: typeof import("./components/PageLoading.vue")["default"];
    README: typeof import("./components/README.md")["default"];
    RouterLink: typeof import("vue-router")["RouterLink"];
    RouterView: typeof import("vue-router")["RouterView"];
    SafeArea: typeof import("./components/SafeArea.vue")["default"];
    SingleScroll: typeof import("./components/SingleScroll.vue")["default"];
  }
}

export {};
